[package]
name = "kbat"
version = "0.1.0"
edition = "2021"

[lib]
name = "libkbat"
path = "src/lib.rs"

[[bin]]
name = "kbat"
path = "src/main.rs"

[dependencies]
byteorder = "1.4.3"
clap = { version = "3.1.9", features = ["derive"] }
log = "0.4.16"
env_logger = "0.9.0"
